development:
 adapter: postgresql
 database: project_development
 host: localhost

test:
 adapter: postgresql
 database: project_test
 host: localhost

production:
 adapter: postgresql
 database: project_production