development:
 adapter: postgresql
 database: earth_development
 host: localhost

test:
 adapter: postgresql
 database: earth_test
 host: localhost

production:
 adapter: postgresql
 database: earth_production
